---
title: "Help"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
---

# Writing centres

You are eligible to work with the writing centre at the college or campus where you're registered.

-   [Innis College Writing Centre](http://innis.utoronto.ca/current-students/academic/innis/writing-centre/), Innis College, Rooms 315 and 321.

-   [New College Writing Centre](http://www.newcollege.utoronto.ca/academics/writing-centre/), Wilson Hall, Rooms 2045 and 2047.

-   [St. Michael's Writing Centre](https://library.stmikes.utoronto.ca/research/), Kelly Library Learning Commons.

-   [Trinity College Writing Centre](http://www.trinity.utoronto.ca/student-services/support/writing-centre.html), Trinity College, Academic Resource Centre, Room 3.

-   [University College Writing Centre](http://www.uc.utoronto.ca/writing-centre), University College, Rooms 259E, 259F, and 259G.

-   [Victoria College Writing Centre](https://www.vic.utoronto.ca/current-students/registrars-office/writing-centre), Online and telephone appointments only during the pandemic.

-   [Woodsworth College Academic Writing Centre](http://www.wdw.utoronto.ca/index.php/current_students/academic_writing_centre/), Woodsworth College, Room 214.

Source: <https://writing.utoronto.ca/writing-centres/arts-and-science/> (not sure when last updated)

# STA303/1002 office hours

Please view the [office hours page](https://q.utoronto.ca/courses/253305/pages/office-hours). Additional TA hours will be offered (TBA).

# The New College Statistics Aid Centre

The New College Statistics Aid Centre (NCSAC) will run via Zoom this semester and will continue to do so until further notice. 

If you are using Zoom **at the University of Toronto** for the first time**,** please visit <https://act.utoronto.ca/zoom-information/> for instructions on activating your Zoom Education account. This licensed account is required in order to participate, *even if you already have an existing Zoom account using your mail.utoronto.ca email*. Please log in to Zoom through [https://utoronto.zoom.us/](https://utoronto.zoom.us/%22) to ensure you are using the provisional managed Zoom Education account.

1.  The students should participate through the Zoom links listed below, corresponding to each TA. **They** **must use their U of T account/email address to participate**. Otherwise, they will not be able to join the room.

2.  Students may have to wait in a Zoom waiting room if the TA is occupied with another student---they will be admitted as soon as the TA is finished.

3.  **Students should type in their "Name -- Course Code" as soon as they enter the room.**

The schedule is as follows; the time zone is EST until March 12 and EDT thereafter.

**January 17 to April 8 (open during Reading Week):**

#### Mondays: 6:00 p.m. -- 9:00 p.m.  *Lei (Liam) Sun\** **(Lei is also one of our STA303 TAs!)**

Zoom link: <https://utoronto.zoom.us/j/84303288261>\
*(Note: No office hours on Family Day, Feb. 21)*

#### Tuesdays: 7:00 p.m. -- 10:00 p.m.  *Angela Wang\**

Zoom link: <https://utoronto.zoom.us/j/82959478053>

#### Wednesdays: 9:00 a.m. -- 12:00 p.m.  *George Stefan*

Zoom link: <https://utoronto.zoom.us/j/82151419286>

#### Thursdays: 2:00 p.m. -- 5:00 p.m.  *David Veitch*

Zoom link: [https://utoronto.zoom.us/j/82238702093](https://utoronto.zoom.us/j/82238702093.)

*(\*) Can help with ACT courses.*

# Mental health supports

You may find yourself feeling overwhelmed, depressed, or anxious. Lots of people feel the same way. There is help available from mental health professionals 24 hours a day via online and phone-based services. Here are some that are available to U of T students:

-   [MySSP - My Student Support Program](https://www.studentlife.utoronto.ca/hwc/myssp) 1-844-451-9700, or outside of Canada call 001-416-380-6578

-   [Good2Talk Student Helpline](https://good2talk.ca/) 1-866-925-5454, or text GOOD2TALK to 686868

-   [Distress Centres of Greater Toronto](https://www.torontodistresscentre.com/) 416-408-4357, or text 45645

There is also the new Navi tool for U of T students, it is a chatbot and your questions are totally anonymous. <http://uoft.me/navi>

The student union are also curating a list here: <https://www.utsu.ca/mental-health/>
