---
title: "Rubric"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
---

# Overview

| **Component**     | **Percentage of project** |
|-------------------|---------------------------|
| Basic checklist   | 5%                        |
| Executive summary | 35%                       |
| Technical report  | 50%                       |
| Code appendix     | 5%                        |
| Ethics statement  | 2%                        |
| Reproducibility   | 3%                        |

# Basic checklist (5%)

+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| **Item**                                                                                                                                                   | **Relative weight** |
+============================================================================================================================================================+=====================+
| **Cover page**                                                                                                                                             |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| Cover page exists as a separate first page AND is professional in appearance (can use provided template for full marks).                                   | 1                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| Title and subtitle together provide an informative introduction to the report.                                                                             | 2                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| Clear from cover page **for** which company the report has been prepared.                                                                                  | 1                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| Clear from cover page **by** which company the report has been prepared.                                                                                   | 1                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| An appropriate submission date is included.                                                                                                                | 1                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| **Overall**                                                                                                                                                |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| Visualizations/tables have captions appropriately numbered and located (viz -- bottom, table -- top)                                                       | 2                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| No code or raw code output (e.g., anything  fixed width font) is included.                                                                                 | 2                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| Variables/data are described in words, not using variable names (e.g., please no "the mean of promotion_var_1 is ...") in text, tables and visualizations. | 2                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| **Executive summary**                                                                                                                                      |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| No more than two pages                                                                                                                                     | 2                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| **Consultant profiles**                                                                                                                                    |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| Every team member has a short professional biography. It can be totally fictitious, it just needs to sound reasonable.                                     | 2                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| **Code**                                                                                                                                                   |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| Code is commented and clearly organized.                                                                                                                   | 2                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| **Submission**                                                                                                                                             |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| A PDF report, created from Knitting to PDF from R Markdown is submitted.                                                                                   | 1                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+

# Executive summary (35%)

+----------------------------------------------+-----------------------------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------------+------------------------------------------------------------------------------+
|                                              | **Poor/Missing**                                                      | **Basic (5--6)**                                                             | **Proficient (7--8)**                                                  | **Outstanding (9--10)**                                                      |
+==============================================+=======================================================================+==============================================================================+========================================================================+==============================================================================+
| **Structure**                                | No or limited use of headings. Structure is not                       | Some organization under sections and headings                                | Some use of headings but may lack                                      | Clear and appropriate headings.                                              |
|                                              | easy to follow.                                                       | but lacks some clarity.                                                      | clarity/organization.                                                  |                                                                              |
|                                              |                                                                       |                                                                              |                                                                        | Structure is logical and well organized.                                     |
|                                              |                                                                       | Executive summary is somewhat difficult to                                   | Executive summary is mostly easy to scan and                           | Executive summary is easy to scan and key information emphasised.            |
|                                              |                                                                       | scan, lack  of emphasis on key information.                                  | key information is emphasised.                                         |                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------------+------------------------------------------------------------------------------+
| **Level of detail appropriate for audience** | Overall, the level of detail is too high or too                       | Level of detail is too low or too high for the                               | Level of detail is mostly appropriate for the                          | Appropriate level of detail for the intended                                 |
|                                              | low for the intended audience.                                        | intended audience in some sections                                           | intended audience                                                      | audience                                                                     |
+----------------------------------------------+-----------------------------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------------+------------------------------------------------------------------------------+
| **Clarity and                                | Tables / figures are inappropriate for the                            | Some tables/figures included are not directly                                | Tables and figures are relevant, but design                            | Tables and figures are relevant,                                             |
| appropriateness:**                           | context.                                                              | relevant to answering the research question(s), and do not effectively       | could be improved to better communicate results as they relate to the  | well-constructed, and communicate the results clearly (in the context of the |
|                                              |                                                                       | communicate the story of the results as they relate to the research          | research question.                                                     | research questions).                                                         |
| **Visualizations and tables**                |                                                                       | question(s).                                                                 |                                                                        |                                                                              |
|                                              |                                                                       |                                                                              | Choices of visualisations / tables may need to                         | They are appropriately chosen for the audience                               |
|                                              |                                                                       | Too many visualisations / tables included that                               | have been curated further.                                             | of the executive summary. With only the most important and interesting       |
|                                              |                                                                       | are not directly relevant and/or should have been further curated.           |                                                                        | visualisations and tables included.                                          |
|                                              |                                                                       |                                                                              |                                                                        |                                                                              |
|                                              |                                                                       |                                                                              |                                                                        | Use of colour is appropriate and consistent.                                 |
|                                              |                                                                       |                                                                              |                                                                        |                                                                              |
|                                              |                                                                       |                                                                              |                                                                        |                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------------+------------------------------------------------------------------------------+
| **Clarity and                                | Results are reported with insufficient                                | Results are                                                                  | Size, direction                                                        | Size and                                                                     |
| appropriateness:**                           | information and context AND/OR too much jargon for audience. Too many | reported but with insufficient information for some important results AND/OR | and confidence (as appropriate) of most significant results are given. | direction of significant results are given in the context of the research    |
|                                              | unimportant or irrelevant results included.                           | not interpreted in context.                                                  |                                                                        | questions.                                                                   |
| **Written comments**                         |                                                                       |                                                                              | Context is stated                                                      |                                                                              |
|                                              |                                                                       | Reported results are not connected to the                                    | for most results.                                                      | Reported results are clearly related to the                                  |
|                                              |                                                                       | research questions.                                                          |                                                                        | research questions. No unimportant or irrelevant results included.           |
|                                              |                                                                       |                                                                              | Relevance to the research questions mostly                             |                                                                              |
|                                              |                                                                       | Language used is inappropriate for the                                       | appropriate.                                                           |                                                                              |
|                                              |                                                                       | audience.                                                                    |                                                                        |                                                                              |
|                                              |                                                                       |                                                                              |                                                                        |                                                                              |
|                                              |                                                                       | Some unimportant or irrelevant results                                       |                                                                        |                                                                              |
|                                              |                                                                       | included.                                                                    |                                                                        |                                                                              |
+----------------------------------------------+-----------------------------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------------+------------------------------------------------------------------------------+
| **Writing mechanics**                        | Considerable writing and grammatical issues that obscure the meaning  | Multiple difficulties in                                                     | Slight difficulty in understanding                                     | Executive summary can be read and                                            |
|                                              | AND/OR lots of slang and inappropriate word choice.                   | understanding due to word choice, grammar and or sentence construction, but  | one or two sections but overall easy to understand.                    | followed with minimal effort.                                                |
|                                              |                                                                       | is overall otherwise understandable.                                         |                                                                        |                                                                              |
|                                              | No bullet points used.                                                |                                                                              | Mostly appropriate use of bullet points and                            | Some grammatical or word choice                                              |
|                                              |                                                                       | Paragraphing / bullet points not                                             | paragraphing. Writing is in full sentences.                            | errors are allowable but must not obstruct meaning.                          |
|                                              |                                                                       | well done.                                                                   |                                                                        |                                                                              |
|                                              |                                                                       |                                                                              |                                                                        | Writing is in full sentences.                                                |
|                                              |                                                                       |                                                                              |                                                                        |                                                                              |
|                                              |                                                                       |                                                                              |                                                                        | Makes appropriate use of bullet points and                                   |
|                                              |                                                                       |                                                                              |                                                                        | paragraphing.                                                                |
+----------------------------------------------+-----------------------------------------------------------------------+------------------------------------------------------------------------------+------------------------------------------------------------------------+------------------------------------------------------------------------------+

*Additional information coming soon*
